### PR TITLE
fix: generating allOf, anyOf, oneOf named enums

### LINKED ISSUE #223: Named Enums not working in anyOf, allOf or oneOf
if i try to generate a named enum inside an anyOf-, allOf- or oneOf-Statement like this:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "namedIntegerEnumTitle": {
      "anyOf": [
        {
          "type": "string",
          "enum": ["one", "two", "three"],
          "title": "NamedInteger",
          "tsEnumNames": ["One", "Two", "Three"]
        },
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "examples": [],
  "required": ["namedIntegerEnumTitle"]
}
```
the generated output looks like this:
```ts
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Test {
  namedIntegerEnumTitle: (NamedInteger | null);
  [k: string]: any;
}
```
The problem is that NamedInteger is referenced but not defined in the output. 

If i use it without anyOf like this:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "namedIntegerEnumTitle": {
      "type": "string",
      "enum": ["one", "two", "three"],
      "title": "NamedInteger",
      "tsEnumNames": ["One", "Two", "Three"]
    }
  },
  "examples": [],
  "required": ["namedIntegerEnumTitle"]
}
```
The generator creates the following output which is correct:
```ts
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Test {
  namedIntegerEnumTitle: NamedInteger;
  [k: string]: any;
}

export const enum NamedInteger {
  One = "one",
  Two = "two",
  Three = "three"
}
```

### PR DESCRIPTION
**Pull request by wadik12**
Fix #223

### CODE REVIEW

File: test/__snapshots__/test/test.ts.md [hunk 1]
```diff
@@ -1272,6 +1272,9 @@ Generated by [AVA](https://ava.li).
       impliedHeterogeneousEnum?: -20.1 | null | "foo" | false;␊
       namedIntegerEnumTitle: NamedInteger;␊
       impliedNamedIntegerEnumTitle: ImpliedNamedInteger;␊
+      oneOfNamedEnum: IntegerOneOfNamedEnum | StringOneOfNamedEnum;␊
+      anyOfNamedEnum: IntegerAnyOfNamedEnum | StringAnyOfNamedEnum;␊
+      allOfNamedEnum?: IntegerAllOfNamedEnum & StringAllOfNamedEnum;␊
```
Comment (bcherny) [inline test/__snapshots__/test/test.ts.md]: Is this right? Does re-running `yarn test -u` make `allOfNamedEnum` required?

Comment (wadik12) [reply test/__snapshots__/test/test.ts.md]: You have right ```allOfNamedEnum``` should be required. Good catch. 👍

**Comment by bcherny** [comment]
Published 8.0.1.
